### PR TITLE
Ensure ~rabbitmq/.erlang.cookie is readable after running a command as root

### LINKED ISSUE #85: Running rabbitmq-plugins as root can create un-readable .erlang.cookie
See rabbitmq/rabbitmq-server#1698

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #85

### CODE REVIEW

**Comment by michaelklishin** [comment]
FTR, at first I had a concern that this effectively limits what user and group the node can use. However, we already effectively do this in the same package script wrapper and maybe that's not a bad thing.

**Comment by lukebakken** [comment]
@michaelklishin that makes sense. I can add a note about that, or I could use token replacement within the script, something like `@RABBITMQ_USER@` and `@RABBITMQ_GROUP@`. Actually, I'll do that, I like it.

**Comment by lukebakken** [comment]
@michaelklishin I just tested a `.deb` package build with the template changes, doing CentOS now.

**Comment by lukebakken** [comment]
@michaelklishin OK just tested on CentOS 7 as well.

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Verified that the fix is effective on CentOS 7.5 with the CentOS 7 RPM.

**Comment by michaelklishin** [comment]
I also have a verbal approval from @dumbbell.

**Comment by lukebakken** [comment]
Thanks @michaelklishin and @dumbbell

**Pull request merged**
