### PR TITLE
Add Travis tests for Pacemaker OCF RA cluster

### PR DESCRIPTION
**Pull request by bogdando**
Add a matrix of two test cases:
* Smoke test: just a check if rabbit cluster assembles.
* Jepsen test: allowed to fail, it's main value is to
  verify cluster auto-healing after consequent network
  partitions and to provide numbers for
  duplicated/lost/recovered/unexpected messages as well.

Make the gate always passing if there is no changes found
to the RabbitMQ OCF RA script in the patch under test.

Here you can find example runs on my forked CI infra:
smoke: https://travis-ci.org/bogdando/rabbitmq-server-release/jobs/178664813
jepsen: https://api.travis-ci.org/jobs/178818386/log.txt?deansi=true

Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>

### CODE REVIEW

**Comment by bogdando** [comment]
@michaelklishin @dmitrymex @binarin

**Comment by michaelklishin** [comment]
@bogdando just to make sure I understand what's expected of us, we should merge this PR and enable Travis for this repo, that's it?

**Comment by bogdando** [comment]
@michaelklishin  yes please, I've also sent an email to the ML

**Comment by michaelklishin** [comment]
@bogdando done and done.

**Comment by michaelklishin** [comment]
@bogdando also, would you like to submit the same PR against `stable`?

**Comment by bogdando** [comment]
makes sens!

**Pull request merged**
