### PR TITLE
Configure shortcuts to run as admin.

### PR DESCRIPTION
**Pull request by hairyhum**
Shortcuts for `rabbitmq-service.bat` should run as admin
because system control tools require admin.
Also make shortcuts run a command prompt and do not exit if there
is an error, so the error can be seen by an operator.

Part of rabbitmq/rabbitmq-server#1324
[#149953545]

### CODE REVIEW

**Review by lukebakken — COMMENTED** [review]
👍 looks good. It'll take a while before I can QA this.

**Review by lukebakken — APPROVED** [review]
👍 tested on Windows 10

**Review by kjnilsson — COMMENTED** [review]
`rabbitmq-service.bat` works fine for starting and stopping but I’m not able to use `rabbitmqctl`, `rabbitmq-plugins.bat` or `rabbitmq-server.bat` as they all fail with an `undef, [{rabbit_something....`

This is on windows 8.

**Review by kjnilsson — APPROVED** [review]
Ignore the previous comment, turns out the erlang version I was testing on was older than the build version as this was a one-off release build.

**Review by michaelklishin — APPROVED** [review]

**Pull request merged**
