### PR TITLE
RPM: Fix service restart after upgrade

### LINKED ISSUE #94: CentOS 7 / yum: Updating stops rabbitmq-server (instead of restarting)
Updating rabbitmq-server on CentOS 7.6 (using the rabbitmq packagecloud repo) when rabbitmq-server is running results in rabbitmq-server being stopped.

While I'm not familiar with reading .spec files, so may have read this wrong, I suspect this is because the update process executes a "stop" (in pre) followed by a "try-restart" (in postun) - the latter has no effect because the service is stopped.

### PR DESCRIPTION
**Pull request by dumbbell**
Before this patch, the package handled the upgrade like this:
1.  It stopped the service in `%pre` so that the service doesn't run with an upgrade in progress.
2.  It used the `try-restart` command in `%postun` to restart the service.

`try-restart` only restarts the service if it is already running. This makes sense when used alone: if the service was not running before an upgrade, you don't want the service to be started in your back. Unfortunately, this was broken because the service was stopped before the upgrade, preventing `try-restart` to do its job. This led to a service left stopped after an upgrade.

Now the new approach is the following one:
1.  It records in `/var/lib/rabbitmq` if the service is running in `%pre`.
2.  It stops the service in `%pre`.
3.  It restarts the service in `%post` if it finds the record made in step 1.

We use `restart` in step 3, not just `start`, just in case the service was already restarted in the middle of the upgrade by e.g. a configuration system.

Restart is handled in `%post`, not `%postun`, because it is also covers a reinstall of the same version. This is ok because the only difference is old now-unreferenced files which are still around in `%post` compared to `%postun`.

While here, systemctl(1) is used in step 1 to stop the service when relevant, instead of always relying on service(8).

Fixes #94.

### CODE REVIEW

**Comment by dumbbell** [comment]
This pull request supersedes #95.

**Review by lukebakken — APPROVED** [review]
Well done @dumbbell

**Comment by lukebakken** [comment]
Backported to `v3.7.x`

**Comment by dumbbell** [comment]
Thank you!

**Pull request merged**
